# modified from https://github.com/simonmichael/hledger/blob/master/.github/workflows/linux.yml

name: CI

defaults:
  run:
    shell: bash

on:
  push:
    branches: [master, ci-*, ci]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [windows-latest]
        agda: ['Agda-2.7.0.1']
      fail-fast: false
    steps:

    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: 📤 Install yq (Windows)
      if: runner.os == 'Windows'
      uses: frenck/action-setup-yq@v1

    - name: 🎛️ Determine which version of Agda to target
      run: |
        STACK_YAML=$(echo stack-9.2-${{ matrix.agda }}.yaml)
        STACK_YAML_ARG="--stack-yaml $(echo stack-9.2-${{ matrix.agda }}.yaml)"

        if [[ ${{ matrix.os }} == "ubuntu-latest" ]]; then
          ARTEFACT="als-${{ matrix.agda }}-ubuntu"
        fi
        if [[ ${{ matrix.os }} == "macos-latest" ]]; then
          ARTEFACT="als-${{ matrix.agda }}-macos-arm64"
        fi
        if [[ ${{ matrix.os }} == "macos-13" ]]; then
          ARTEFACT="als-${{ matrix.agda }}-macos-x64"
        fi
        if [[ ${{ matrix.os }} == "windows-latest" ]]; then
          ARTEFACT="als-${{ matrix.agda }}-windows"
        fi
        
        echo STACK_YAML_ARG="${STACK_YAML_ARG}" >> "${GITHUB_ENV}"
        echo STACK_YAML="${STACK_YAML}"         >> "${GITHUB_ENV}"
        echo ARTEFACT="${ARTEFACT}"             >> "${GITHUB_ENV}"

    - name: 🎛️ Determine Stack resolver & GHC version
      run: |
        STACK_RESOLVER=$(yq .resolver $STACK_YAML)
        GHC_VERSION=$(echo $(yq .compiler $STACK_YAML) | cut -c 5-)
        echo STACK_RESOLVER="${STACK_RESOLVER}" >> "${GITHUB_ENV}"
        echo GHC_VERSION="${GHC_VERSION}"       >> "${GITHUB_ENV}"

    - name: 🏗 Setup Haskell
      if : runner.os == 'macOS'
      uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ env.GHC_VERSION }}
        enable-stack: true
        stack-version: 'latest'
  
    - name: 🎛️ Determine Stack root
      run: |
        STACK_ROOT="$(stack path $STACK_YAML_ARG --stack-root)"
        echo STACK_ROOT="${STACK_ROOT}"         >> "${GITHUB_ENV}"

    - name: 🔍 Review all variables
      run: |
        echo "STACK_YAML      = ${STACK_YAML}"
        echo "STACK_YAML_ARG  = ${STACK_YAML_ARG}"
        echo "STACK_RESOLVER  = ${STACK_RESOLVER}"
        echo "ARTEFACT        = ${ARTEFACT}"
        echo "GHC_VERSION     = ${GHC_VERSION}"
        echo "STACK_ROOT      = ${STACK_ROOT}"

    # things to be restored:
    # Include STACK_RESOLVER in cache key, otherwise caches accumulate build products for different resolvers.

    - name: 💾 Restore cached stack global package db
      id:   stack-global
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.STACK_ROOT }}
        key: ${{ matrix.os }}-stack-resolver-${{ env.STACK_RESOLVER }}-global-${{ hashFiles('**.yaml') }}-${{ matrix.agda }}
        restore-keys: |
             ${{ matrix.os }}-stack-resolver-${{ env.STACK_RESOLVER }}-global

    - name: 💾 Restore cached .stack-work
      id:   stack-work
      uses: actions/cache/restore@v4
      with:
        path: .stack-work
        key: ${{ matrix.os }}-stack-resolver-${{ env.STACK_RESOLVER }}-work-${{ hashFiles('**.yaml') }}-${{ matrix.agda }}
        restore-keys: |
             ${{ matrix.os }}-stack-resolver-${{ env.STACK_RESOLVER }}-work

    # actions:
    - name: ⚙️ Set PKG_CONFIG_PATH for the ICU library (on macOS)
      if: runner.os == 'macOS'
      run: |
        echo PKG_CONFIG_PATH="$(brew --prefix)/opt/icu4c/lib/pkgconfig" >> "${GITHUB_ENV}"

    - name: 📥 Install the icu library (on Windows)
      if: runner.os == 'Windows'
      run: |
        stack exec $STACK_YAML_ARG -- pacman -S --noconfirm mingw-w64-x86_64-icu mingw-w64-x86_64-pkgconf

    - name: 📸 Build Snapshot
      run: stack build $STACK_YAML_ARG --no-terminal --only-snapshot -j1

    - name: 🏗️ Build Dependencies
      run: stack build $STACK_YAML_ARG --no-terminal --only-dependencies

    - name: 🏗️ Build ALS
      run: stack build $STACK_YAML_ARG
  
    - name: 🏗️ Build Testings
      run: stack build $STACK_YAML_ARG --test --no-terminal --only-dependencies
  
    # things to be cached

    - name: 💾 Cache stack global package db
      if:   always() && steps.stack-global.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ env.STACK_ROOT }}
        key: ${{ steps.stack-global.outputs.cache-primary-key }}

    - name: 💾 Cache .stack-work
      if:   always() && steps.stack-work.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: .stack-work
        key: ${{ steps.stack-work.outputs.cache-primary-key }}


    - name: 📦 Bundle executable, DLLs and data files (on macOS)
      if: runner.os == 'macOS'
      run: |  # Bundle icu4c DLLs

        # see if icu4c has been installed
        if [ "$(brew list | grep icu4c)" = "" ]
            then
                echo "installing icu4c"
                brew install icu4c
        fi

        # get the directory of the DDLs we want (icuuc, icui18n, icudata)
        dylib_dir=$(dirname "$(brew list icu4c | grep icuuc.dylib)")
        echo "dylib_dir: $dylib_dir"

        # find the path of "als"
        executable=$(find "$(stack path $STACK_YAML_ARG --local-install-root)"/bin -name "als")
        echo "executable: $executable"

        # remove the old dylib, and make a new one
        rm -rf dylib
        mkdir dylib

        ################################################################################
        # icuuc
        ################################################################################

        icuuc_id=$(otool -L "$executable" | grep icuuc | awk '{print $1}')
        icuuc_id_basename=$(basename "$icuuc_id")

        icuuc_path=$dylib_dir/$icuuc_id_basename
        icuuc_path_new=dylib/$icuuc_id_basename
        icuuc_id_new=@loader_path/dylib/$icuuc_id_basename

        # copy icuuc to the new directory
        cp "$icuuc_path" "$icuuc_path_new"

        # change icuuc's ID referenced by ALS
        install_name_tool -change "$icuuc_id" "$icuuc_id_new" "$executable"

        echo "icuuc referenced by ALS"
        echo "    old ID  : $icuuc_id"
        echo "    new ID  : $icuuc_id_new"
        echo "    old path: $icuuc_path"
        echo "    new path: $icuuc_path_new"

        ################################################################################
        # icui18n
        ################################################################################

        icui18n_id=$(otool -L "$executable" | grep icui18n | awk '{print $1}')
        icui18n_id_basename=$(basename "$icui18n_id")

        icui18n_path=$dylib_dir/$icui18n_id_basename
        icui18n_path_new=dylib/$icui18n_id_basename
        icui18n_id_new=@loader_path/dylib/$icui18n_id_basename

        # copy icui18n to the new directory
        cp "$icui18n_path" "$icui18n_path_new"

        # change icui18n's ID referenced by ALS
        install_name_tool -change "$icui18n_id" "$icui18n_id_new" "$executable"

        echo "icui18n referenced by ALS"
        echo "    old ID  : $icui18n_id"
        echo "    new ID  : $icui18n_id_new"
        echo "    old path: $icui18n_path"
        echo "    new path: $icui18n_path_new"

        ################################################################################
        # icudata
        ################################################################################

        # otool -L "$icui18n_id" | grep icudata | awk '{print $1}'
        icudata_id=$(otool -L "$icuuc_path" | grep icudata | awk '{print $1}')
        icudata_id_basename=$(basename "$icudata_id")

        icudata_path=$dylib_dir/$icudata_id_basename
        icudata_path_new=dylib/$icudata_id_basename

        # copy icudata to the new directory
        cp "$icudata_path" "$icudata_path_new"

        # no need of changing the ID because supposely it's already of "@loader_path"

        echo "icudata referenced by icuuc"
        echo "    old ID    : $icudata_id"
        echo "    old path  : $icudata_path"
        echo "    new path  : $icudata_path_new"

    - name: 📦 Bundle executable, DLLs and data files (on Linux and macOS)
      if: runner.os != 'Windows'
      id: zip
      run: |
        # locate the data-dir
        datadir=$(find "$(stack path $STACK_YAML_ARG --snapshot-install-root)/share" -type d -name "Agda-*")
        echo "datadir: $datadir"

        # locate the executable
        executable=$(find "$(stack path $STACK_YAML_ARG --local-install-root)/bin" -name "als")
        echo "executable: $executable"

        # make a temporary directory for compresssing
        mkdir zip
        cp -r "$datadir" zip/data
        if [[ ${{ runner.os }} == "macOS" ]]; then
            cp -r dylib zip/dylib
        fi
        cp "$executable" zip/

        # compress
        cd zip
        zip -r $ARTEFACT.zip ./*
        cd ..
        mv zip/$ARTEFACT.zip .
        

    - name: 📦 Bundle executable, DLLs and data files (on Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # locate the data-dir
        $snapshot = (stack path $STACK_YAML_ARG --snapshot-install-root)
        $datadir = (ls $snapshot\share *Agda-* -Recurse -Directory).FullName

        # locate the executable
        $local = (stack path $STACK_YAML_ARG --local-install-root)
        $executable = (ls $local\bin *als.exe* -Recurse -File).FullName

        # make a temporary directory for compresssing
        mkdir zip
        cp -r $datadir zip/data
        cp $executable zip/

        # include text-icu DLLs
        $mingw64bin = (stack path $STACK_YAML_ARG --extra-library-dirs).split(", ") -match "\\bin"
        cp (ls $mingw64bin *libicudt*) zip/
        cp (ls $mingw64bin *libicuin*) zip/
        cp (ls $mingw64bin *libicuuc*) zip/
        ls zip

        # compress
        cd zip
        Compress-Archive * "$($env:ARTEFACT).zip"
        cd ..
        ls zip
        mv zip/"$($env:ARTEFACT).zip" .
        ls 
  
  
    - name: 🧪 Run tests
      run: stack test $STACK_YAML_ARG --ta --als-path=zip/als
  
    # release (optional)
    - name: 🚢 Release Artifacts
      if: startsWith(github.ref, 'refs/tags/v') # so that only commits with a git tag would upload artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.ref_name }} $ARTEFACT.zip --clobber